FROM centos:7

COPY conf/nginx.repo /etc/yum.repos.d/nginx.repo

RUN \
   yum install -y nginx && \
   yum install -y yum-utils && \
   yum install -y epel-release && \
   yum install -y http://rpms.remirepo.net/enterprise/remi-release-7.rpm && \
   yum-config-manager ––enable remi–php72 && \
   yum install -y php php-common php-opcache php-mcrypt php-cli php-gd php-curl php-mysql php-fpm

RUN mkdir /nginx_php
COPY conf/nginx.conf /etc/nginx/conf.d/default.conf

COPY conf/start.sh /start.sh

RUN chmod +x /start.sh

CMD /start.sh
