<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW0YZYhI\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW0YZYhI/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerW0YZYhI.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerW0YZYhI\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerW0YZYhI\appAppKernelProdContainer([
    'container.build_hash' => 'W0YZYhI',
    'container.build_id' => '744a54d1',
    'container.build_time' => 1676452713,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW0YZYhI');
